parameters:
  analysis_color:
    polar: 'magenta'
    nonpolar: 'yellow'
    charged: 'red'
    hydrophobic: 'green'
    positively_charged: 'blue'
    negatively_charged: 'red'

  # define generic color
  # the assigment order is the one shown in the list
  # When few colors are needed, the first ones in the list are used
  generic_colors:
    0: "FF0000"
    1: "00FF00"
    2: "0000FF"
    3: "FFFF00"
    4: "FF00FF"
    5: "00FFFF"
    6: "FF8888"
    7: "88FF88"
    8: "8888FF"
    9: "FFFF88"
    10: "FF88FF"
    11: "88FFFF"
    12: "FF3366"
    13: "33FF66"
    14: "3366FF"
    15: "FF6633"
    16: "66FF33"
    17: "6633FF"
    18: "880000"
    19: "008800"

  protein_colors:
    20:
      A: "CCFFFF"
      R: "E60606"
      N: "FF9900"
      D: "FFCC99"
      C: "00FFFF"
      E: "FFCC00"
      Q: "FF6600"
      G: "00FF00"
      H: "FFFF99"
      I: "000088"
      L: "3366FF"
      K: "C64200"
      M: "99CCFF"
      F: "00CCFF"
      P: "FFFF00"
      S: "CCFF99"
      T: "00FF99"
      W: "CC99FF"
      Y: "CCFFCC"
      V: "0000FF"
    2:
      P: "0000FF"
      H: "FF0000"
    5:
      A: "FF0000"
      R: "00FF00"
      C: "0000FF"
      T: "FFFF00"
      D: "00FFFF"
    6:
      A: "FF0000"
      R: "00FF00"
      P: "0000FF"
      N: "8888FF"
      T: "FFFF00"
      D: "00FFFF"
    3IMG:
      P: "E60606"
      N: "FFFF00"
      H: "3366FF"
    5IMG:
      G: "E60606"
      C: "E60606"
      E: "E60606"
      M: "E60606"
      F: "E60606"
    11IMG:
      A: "1B04AE"
      F: "00CCFF"
      C: "CCECFF"
      G: "00FF00"
      S: "89F88B"
      W: "CC99FF"
      Y: "CCFFCC"
      P: "FFFF00"
      D: "FFCC00"
      N: "F4A504"
      H: "EC1504"
    Murphy15:
      L: "FF0000"
      C: "00FF00"
      A: "0000FF"
      G: "FFFF00"
      S: "00FFFF"
      T: "FF00FF"
      P: "880000"
      F: "008800"
      W: "000088"
      E: "888800"
      D: "008888"
      N: "880088"
      Q: "FF8888"
      K: "88FF88"
      H: "8888FF"
    Murphy10:
      L: "FF0000"
      C: "00FF00"
      A: "0000FF"
      G: "FFFF00"
      S: "00FFFF"
      P: "880000"
      F: "008800"
      E: "888800"
      K: "88FF88"
      H: "8888FF"
    Murphy8:
      L: "FF0000"
      A: "0000FF"
      S: "00FFFF"
      P: "880000"
      F: "0000FF"
      E: "008800"
      K: "88FF88"
      H: "0000FF"
    Murphy4:
      L: "00FF00"
      A: "00FFFF"
      F: "FF0000"
      E: "0000FF"
    Murphy2:
      P: "FF0000"
      E: "0000FF"
    Wang5:
      I: "FF0000"
      A: "00FF00"
      G: "FFFF00"
      E: "0000FF"
      K: "00FFFF"
    Wang5v:
      I: "FF0000"
      L: "FFFF00"
      A: "00FF00"
      E: "0000FF"
      K: "00FFFF"
    Wang3:
      I: "FF0000"
      A: "00FF00"
      E: "0000FF"
    Wang2:
      I: "FF0000"
      A: "0000FF"
    Li10:
      C: "FF0000"
      Y: "FFFF00"
      L: "FF00FF"
      V: "FF8888"
      G: "00FFFF"
      P: "88FF88"
      S: "00FF00"
      N: "8888FF"
      E: "0000FF"
      K: "88FFFF"
    Li5:
      Y: "FFFF00"
      I: "FF0000"
      G: "00FFFF"
      S: "00FF00"
      E: "0000FF"
    Li4:
      Y: "FFFF00"
      I: "FF0000"
      S: "00FF00"
      E: "0000FF"
    Li3:
      I: "FF0000"
      S: "00FF00"
      E: "0000FF"
