parameters:
  # triplets is the array containing the genetic codes
  triplets_combinations: ["TTT ", "TTC ", "TTA ", "TTG ", "TCT ", "TCC ", "TCA ", "TCG ",
                          "TAT ", "TAC ", "TAA ", "TAG ", "TGT ", "TGC ", "TGA ", "TGG ", "CTT ", "CTC ",
                          "CTA ", "CTG ", "CCT ", "CCC ", "CCA ", "CCG ", "CAT ", "CAC ", "CAA ", "CAG ",
                          "CGT ", "CGC ", "CGA ", "CGG ", "ATT ", "ATC ", "ATA ", "ATG ", "ACT ", "ACC ",
                          "ACA ", "ACG ", "AAT ", "AAC ", "AAA ", "AAG ", "AGT ", "AGC ", "AGA ", "AGG ",
                          "GTT ", "GTC ", "GTA ", "GTG ", "GCT ", "GCC ", "GCA ", "GCG ", "GAT ", "GAC ",
                          "GAA ", "GAG ", "GGT ", "GGC ", "GGA ", "GGG "]
